### ISSUE TITLE
No module named 'chumpy'

### ISSUE THREAD

**Issue by MohamedAliRashad** [hassony2/manopth#12]
I found that this is a python2 package for auto differentiation, is there any hope for python3 support ?

**Comment by MohamedAliRashad** [comment]
The solution i found was to install it with this command

`pip3 install git+https://github.com/scottandrews/chumpy.git@fe51783e0364bf1e9b705541e7d77f894dd2b1ac`

From https://github.com/mattloper/chumpy/issues/40

**Comment by hassony2** [comment]
This is right, i also have a repo which serves the same purpose as can be seen in [environment.yml](https://github.com/hassony2/manopth/blob/c1873746b8659ea96d9537475996e5fcba1ff2db/environment.yml#L12).

Glad you solved it !
