### ISSUE TITLE
It seems that your have reused some of our code.

### ISSUE THREAD

**Issue by MandyMo** [hassony2/manopth#3]
It seems that, you have copied some parts of the code in the following project 'https://github.com/MandyMo/pytorch_HMR'.

It would be better if you acknowledge the above code.

**Comment by hassony2** [comment]
Hi !

You are very right ! Originally I was using opencv for the part but your code is much more  elegant then going back and forth to numpy.
I have updated the acknowledgements to credit you in the [README](https://github.com/hassony2/manopth/blob/master/README.md) as well as at the top of the [rodrigues_layer.py file](https://github.com/hassony2/manopth/blob/master/manopth/rodrigues_layer.py) where I am reusing the parts of your code.

Thank you for making your code available and definitely let me know if the current acknowledgements 
 work for you, or if you would like me to add anything else more specifically !

Best,

Yana

**Comment by MandyMo** [comment]
thank you.

**Comment by MandyMo** [comment]
I have updated the readme file of our project repository. Thanks a lot if you could follow the citation request accordingly.
