### ISSUE TITLE
Gives the demo to train on my own data-set?

### ISSUE THREAD

**Issue by momo1986** [hassony2/manopth#4]
Hello,
if I want to use the training software to implement my own model?
Thanks a lot for sharing.
Is there any demo that i can try?
Thanks 
Momo

**Comment by hassony2** [comment]
Hi @momo1986 !

The training code will come later, once I'm done cleaning :)
I'll keep you posted !

Best,

Yana

**Comment by momo1986** [comment]
Hello, @hassony2 .

Looks like there is a demo to build hand reconstruction model？

For a video with hand motion, how can this program be applied to fit?

Thanks & Regards!
Neo

**Comment by hassony2** [comment]
Hi @momo1986, 

You can find the training code to perform RGB image --> mano shape/pose estimation at  [obman_train](https://github.com/hassony2/obman_train). 
Once you have a trained model you could apply it frame-by-frame on your video.
You might be interested in the model `release_models/hands_only/checkpoint.pth.tar` also available if you follow the instructions from the [obman_train repository](https://github.com/hassony2/obman_train).

Does this answer your question ?

Best,

Yana

**Comment by momo1986** [comment]
Hello Yana,

Thanks a lot for your patient answer and nice guide.

Hopes for further communication on hand pose and human pose estimation.

**Comment by hassony2** [comment]
Sure ! Looking forward to it :)
